// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

//Storing all the gameplay tags in one place


HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Player);

#pragma region Player Status
HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Player_Status);

HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Player_Status_Dead);
HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Player_Status_Downed);
HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Player_Status_Menu);

#pragma endregion

HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effect);

#pragma region Effects

HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effect_Damage);
HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effect_Heal);
HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effect_Stun);
HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effect_Slow);
HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effect_Charm);
HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effect_Fear);
HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effect_Taunt);

#pragma endregion

HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability);

#pragma region Ability Tags

HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Firing);
HORDESHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Reload);

#pragma endregion
